### ISSUE TITLE
Add demo video to front page

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime.github.io#28]
https://www.youtube.com/watch?v=Qhr_aVBCZPw

@amylily1011 

Do you think you could take this on? The site is all in html and built on github pages?

**Comment by amylily1011** [comment]
Sure! I’ll be more than happy to. I’ll have a look in a little bit :).

**Comment by lukehinds** [comment]
thanks @amylily1011 

Anything else you see that you feel could be improved, please hack away!
